# Site settings
title: Un sitio web para presentarte
description: Genera tu presencia en internet 
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Dra. Katy Castro
user_description: Médico General
user_title: Médico General 
email: anon@anon.com
twitter_username: 
github_username:  
gplus_username:  

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
